#!/bin/sh

. /etc/openwrt_release

case $DISTRIB_TARGET in
	*76x8*) exit 0 ;;
esac

[ -f /etc/.config.lock ] && exit 0

cat << 'EOF' > /etc/mptcpd/mptcpd.conf
[core]
log=syslog
plugin-dir=/usr/lib/mptcpd
path-manager=addr_adv
addr-flags=subflow,fullmesh
notify-flags=existing,skip_link_local,skip_loopback,check_route
load-plugins=addr_adv,sspi
EOF

# Hotplug action
cat << 'EOF' > /etc/hotplug.d/iface/80-mptcp
#!/bin/sh

do_run(){
	[ -x /usr/bin/mptcpd ] && {
		ip mptcp endpoint flush
		/etc/init.d/mptcpd restart
	}
}

sleep 10 && do_run &
EOF
