#!/bin/sh

CONFIG=/etc/3proxy.cfg
LANIP="$(uci -q get network.lan.ipaddr)"
LANIP6="$(uci -q get network.globals.ula_prefix | awk -F [\/] '{print $1"1"}')"

cat << EOF > $CONFIG
plugin /usr/lib/3proxy/TransparentPlugin.ld.so transparent_plugin
daemon
nserver 127.0.0.1
nscache 65536
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
log @3proxy
auth iponly
allow *
socks -64 -i127.0.0.1 -p1090 -n
socks -64 -i::1 -p1090 -n
transparent
tcppm -i${LANIP} 3128 127.0.0.1 1090
tcppm -i${LANIP6} 3128 ::1 1090
notransparent
EOF
