#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

if ! [ -x /usr/sbin/wpad -o -x /usr/sbin/hostapd ]; then
	exit 0
fi

MACHINE=$(awk '{print $2}' /sys/firmware/devicetree/base/model)
SUFFIX=$(awk -F [:] '{print toupper($4$5$6)}' /sys/class/net/eth0/address)

# 5 radios enough devices :)
enable_wifi(){
	for r in $(seq 0 5); do
		case $(uci -q get wireless.radio${r}.band) in
			2g)
				uci -q set wireless.radio${r}.country='RU'
				uci -q set wireless.radio${r}.noscan='1'
				uci -q set wireless.default_radio${r}.ssid=${MACHINE:=WIFI}_2G_${SUFFIX:=$r}
				uci -q delete wireless.radio${r}.disabled='1'
			;;
			5g)
				uci -q set wireless.radio${r}.country='RU'
				uci -q set wireless.default_radio${r}.ssid=${MACHINE:=WIFI}_5G_${SUFFIX:=$r}
				uci -q delete wireless.radio${r}.disabled='1'
			;;
		esac
	done

	uci -q commit wireless
	wifi
}

# More chips slowly start radio
sleep 30 && enable_wifi &
