#!/bin/sh
uci batch << EOF
delete network.globals
delete network.wan6
set network.wwan=interface
set network.wwan.proto='modemmanager'
set network.wwan.device='/sys/devices/platform/101c0000.ehci/usb1/1-1/1-1.3'
set network.wwan.iptype='ipv4'
set network.wwan.auth='none'
commit network
EOF
