#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

# genetate ula prefix from default ll address
ula=$(awk -F [:] '{print "fc00:" tolower($3$4) ":" tolower($5$6) "::/48"}' /sys/class/net/eth0/address)
# config network
uci batch << EOF
delete network.wan6
set network.wan.metric='10'
set network.globals.ula_prefix=$ula
del dhcp.lan.ra
del dhcp.lan.ra_slaac
del dhcp.lan.ra_flags
del dhcp.lan.dhcpv6
EOF


board="$(cat /tmp/sysinfo/board_name)"

setup_macs(){
        local board="$1"
        local lan_mac=""
        local wan_mac=""
        local label_mac=""
        case $board in
		huastlink,hc-g60)
			label_mac=$(mtd_get_mac_binary "Factory" 0x4)
			uci add network device
			uci set network.@device[-1].name=wwan
			uci set network.@device[-1].macaddr="$(macaddr_add $label_mac 5)"
		;;
                zbtlink,zbt-z8109ax-nand-all)
                        label_mac=$(mtd_get_mac_binary "Factory" 0x4)
			for c in 0 1; do
				uci add network device
				uci set network.@device[-1].name=cel${c}
				uci set network.@device[-1].macaddr="$(macaddr_add $label_mac $((5+$c)))"
                        done
                ;;
        esac
}

setup_macs $board
uci commit network


# fix error ifup L850 modem
cat << 'EOF' > /etc/hotplug.d/iface/01-mm-error
#!/bin/sh

error(){
        ERROR_CODE=$(ifstatus $1 | jsonfilter -e '@["errors"][*]["code"]')
        case "$ERROR_CODE" in
		MM_3GPP_OPERATOR_REGISTRATION_FAILED|\
		MM_FAILED_SETTING_PREFERRED_MODE)
			ifup $1
		;;
	esac
}

[ "$ACTION" = "ifup-failed" ] && {
	sleep 10 && error $INTERFACE &
}
EOF

echo '/etc/hotplug.d/iface/01-mm-error' >> /etc/sysupgrade.conf
