#!/bin/sh

# 5 radios enough devices :)
for r in $(seq 0 5); do
	case $(uci -q get wireless.radio${r}.band) in
		2g)
			uci -q set wireless.radio${r}.country='RU'
			uci -q set wireless.radio${r}.noscan='1'
			uci -q set wireless.radio${r}.htmode='HT40'
			uci -q delete wireless.radio${r}.disabled='1'
		;;
		5g)
			uci -q set wireless.radio${r}.country='RU'
			uci -q delete wireless.radio${r}.disabled='1'
		;;
	esac
done

uci -q commit wireless
wifi
