#!/bin/sh

uci batch << EOF
set smstools3.@sms[0]=sms
set smstools3.@sms[0].decode_utf='1'
set smstools3.@sms[0].storage='temporary'
set smstools3.@sms[0].net_check='0'
set smstools3.@sms[0].loglevel='5'
set smstools3.@sms[0].led_enable='1'
set smstools3.@sms[0].led='green:wifi'
set smstools3.@sms[0].device='/dev/ttyMODEM2'
EOF
