#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

CONFIG=/etc/3proxy.cfg
LANIP="$(uci -q get network.lan.ipaddr)"
LANIP6="$(uci -q get network.globals.ula_prefix | awk -F [\/] '{print $1"1"}')"

uci set 3proxy.@3proxy[0].mptcp='1'
uci commit 3proxy

cat << EOF > $CONFIG
plugin /usr/lib/3proxy/TransparentPlugin.ld.so transparent_plugin
daemon
nserver 127.0.0.1
nscache 65536
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
log @3proxy
auth iponly
allow *
# parent 1000 socks5+ \${SERVER_IP} \${SERVER_PORT}
socks -64 -i127.0.0.1 -p1090 -n
#socks -64 -i::1 -p1090 -n
transparent
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i${LANIP} 3128 127.0.0.1 1090
#tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i${LANIP6} 3128 ::1 1090
notransparent
EOF

echo "$CONFIG" >> /etc/sysupgrade.conf
