#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

uci batch << EOF
set dhcp.@dnsmasq[0].domainneeded='1'
set dhcp.@dnsmasq[0].localise_queries='1'
set dhcp.@dnsmasq[0].strictorder='1'
set dhcp.@dnsmasq[0].localservice='1'
set dhcp.@dnsmasq[0].rebind_protection='0'
commit dhcp
EOF

