#!/bin/sh

[ -f /etc/.config.lock ] && exit 0


. /etc/openwrt_release

case $DISTRIB_RELEASE in
	25.12.*|SNAPSHOT*)
		FILE=/etc/apk/keys/132lan.pem
cat << 'EOF' > $FILE
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC0R0QAKZD4FiUtlcn7T9/hqIGtoO
fg1zqH+k5xEYSMphv8Hu4VxSsxWFuOqAc5y6k/gVpgrePsY+G6HUyX+vTQ==
-----END PUBLIC KEY-----
EOF
		echo "https://openwrt.132lan.ru/packages/${DISTRIB_RELEASE%.*}/packages/${DISTRIB_ARCH}/modemfeed/packages.adb" >> /etc/apk/repositories.d/customfeeds.list
	;;
	24.10.*)
		FILE=/etc/opkg/keys/62705f7e940c2737
cat << 'EOF' > $FILE
untrusted comment: public key 62705f7e940c2737
RWRicF9+lAwnN+JSxJwzpTJAAVHOBCbXgixOt2lLKZM4vhq42tMShgmc
EOF
	echo "src/gz modemfeed http://openwrt.132lan.ru/packages/${DISTRIB_RELEASE%.*}/packages/${DISTRIB_ARCH}/modemfeed" >> /etc/opkg/customfeeds.conf
	echo "#src/gz modem_kmod http://openwrt.132lan.ru/packages/${DISTRIB_RELEASE%.*}/packages/${DISTRIB_ARCH}/kmods/${DISTRIB_RELEASE}/${DISTRIB_TARGET##*/}" >> /etc/opkg/customfeeds.conf
	;;
	21.02*|23.05*)

		FILE=/etc/opkg/keys/62705f7e940c2737
cat << 'EOF' > $FILE
untrusted comment: public key 62705f7e940c2737
RWRicF9+lAwnN+JSxJwzpTJAAVHOBCbXgixOt2lLKZM4vhq42tMShgmc
EOF
		echo "src/gz modemfeed http://openwrt.132lan.ru/packages/${DISTRIB_RELEASE%.*}/packages/${DISTRIB_ARCH}/modemfeed" >> /etc/opkg/customfeeds.conf
	;;

esac

