#!/bin/sh

[ -f /etc/.config.lock ] && exit 0


. /etc/openwrt_release

case $DISTRIB_RELEASE in
	25.12*|SNAPSHOT*)
		FILE=/etc/apk/keys/132lan.pem
cat << 'EOF' > $FILE
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC0R0QAKZD4FiUtlcn7T9/hqIGtoO
fg1zqH+k5xEYSMphv8Hu4VxSsxWFuOqAc5y6k/gVpgrePsY+G6HUyX+vTQ==
-----END PUBLIC KEY-----
EOF
		echo "https://openwrt.132lan.ru/packages/${DISTRIB_RELEASE%.*}/packages/${DISTRIB_ARCH}/modemfeed/packages.adb" >> /etc/apk/customfeeds.conf
	;;
	*)
		FILE=/etc/opkg/keys/0c045b2ab5a62241
cat << 'EOF' > $FILE
untrusted comment: public key 0c045b2ab5a62241
RWQMBFsqtaYiQUBLJyFWcco98vKKEN9I1QRAonQBKTQu0yAzNOyPuN1s
EOF

		FILE=/etc/opkg/keys/62705f7e940c2737
cat << 'EOF' > $FILE
untrusted comment: public key 62705f7e940c2737
RWRicF9+lAwnN+JSxJwzpTJAAVHOBCbXgixOt2lLKZM4vhq42tMShgmc
EOF
		echo "src/gz modemfeed http://openwrt.132lan.ru/packages/${DISTRIB_RELEASE%.*}/packages/${DISTRIB_ARCH}/modemfeed" >> /etc/opkg/customfeeds.conf
	;;
esac

