#!/bin/sh

[ -f /etc/.config.lock -a ! -x /usr/bin/youtubeUnblock ] && exit 0

set_config(){
uci batch << EOF
set youtubeUnblock.@section[0].name='YouTube'
add youtubeUnblock section
set youtubeUnblock.@section[-1].name='CallsWhatsAppTelegram'
set youtubeUnblock.@section[-1].tls_enabled='0'
set youtubeUnblock.@section[-1].all_domains='0'
add_list youtubeUnblock.@section[-1].sni_domains='cdn-telegram.org' 
add_list youtubeUnblock.@section[-1].sni_domains='comments.app'
add_list youtubeUnblock.@section[-1].sni_domains='contest.com'
add_list youtubeUnblock.@section[-1].sni_domains='fragment.com'
add_list youtubeUnblock.@section[-1].sni_domains='graph.org'
add_list youtubeUnblock.@section[-1].sni_domains='quiz.directory'
add_list youtubeUnblock.@section[-1].sni_domains='t.me'
add_list youtubeUnblock.@section[-1].sni_domains='tdesktop.com'
add_list youtubeUnblock.@section[-1].sni_domains='telega.one'
add_list youtubeUnblock.@section[-1].sni_domains='telegra.ph'
add_list youtubeUnblock.@section[-1].sni_domains='telegram-cdn.org'
add_list youtubeUnblock.@section[-1].sni_domains='telegram.dog'
add_list youtubeUnblock.@section[-1].sni_domains='telegram.me'
add_list youtubeUnblock.@section[-1].sni_domains='telegram.org'
add_list youtubeUnblock.@section[-1].sni_domains='telegram.space'
add_list youtubeUnblock.@section[-1].sni_domains='telesco.pe'
add_list youtubeUnblock.@section[-1].sni_domains='tg.dev'
add_list youtubeUnblock.@section[-1].sni_domains='tx.me'
add_list youtubeUnblock.@section[-1].sni_domains='usercontent.dev'
add_list youtubeUnblock.@section[-1].sni_domains='graph.facebook.com'
add_list youtubeUnblock.@section[-1].sni_domains='whatsapp.biz'
add_list youtubeUnblock.@section[-1].sni_domains='whatsapp.com'
add_list youtubeUnblock.@section[-1].sni_domains='whatsapp.net'
set youtubeUnblock.@section[-1].sni_detection='parse'
set youtubeUnblock.@section[-1].quic_drop='0'
set youtubeUnblock.@section[-1].udp_mode='fake'
set youtubeUnblock.@section[-1].udp_faking_strategy='none'
set youtubeUnblock.@section[-1].udp_fake_seq_len='6'
set youtubeUnblock.@section[-1].udp_fake_len='64'
set youtubeUnblock.@section[-1].udp_filter_quic='disabled'
set youtubeUnblock.@section[-1].enabled='1'
set youtubeUnblock.@section[-1].udp_stun_filter='1'
add youtubeUnblock section
set youtubeUnblock.@section[-1].name='RutrackerLostFilmSpeedTest'
set youtubeUnblock.@section[-1].enabled='1'
set youtubeUnblock.@section[-1].tls_enabled='1'
set youtubeUnblock.@section[-1].fake_sni='1'
set youtubeUnblock.@section[-1].faking_strategy='pastseq'
set youtubeUnblock.@section[-1].fake_sni_seq_len='1'
set youtubeUnblock.@section[-1].fake_sni_type='default'
set youtubeUnblock.@section[-1].frag='tcp'
set youtubeUnblock.@section[-1].frag_sni_reverse='1'
set youtubeUnblock.@section[-1].frag_sni_faked='0'
set youtubeUnblock.@section[-1].frag_middle_sni='1'
set youtubeUnblock.@section[-1].frag_sni_pos='1'
set youtubeUnblock.@section[-1].seg2delay='0'
set youtubeUnblock.@section[-1].fk_winsize='0'
set youtubeUnblock.@section[-1].synfake='0'
set youtubeUnblock.@section[-1].sni_detection='parse'
set youtubeUnblock.@section[-1].all_domains='0'
set youtubeUnblock.@section[-1].quic_drop='1'
add_list youtubeUnblock.@section[-1].sni_domains='rutracker.org'
add_list youtubeUnblock.@section[-1].sni_domains='lostfilm.tv'
add_list youtubeUnblock.@section[-1].sni_domains='speedtest.net'
add youtubeUnblock section
set youtubeUnblock.@section[-1].name='Discord'
set youtubeUnblock.@section[-1].tls_enabled='1'
set youtubeUnblock.@section[-1].all_domains='0'
set youtubeUnblock.@section[-1].sni_detection='parse'
set youtubeUnblock.@section[-1].quic_drop='1'
set youtubeUnblock.@section[-1].enabled='1'
set youtubeUnblock.@section[-1].udp_stun_filter='1'
set youtubeUnblock.@section[-1].fake_sni='1'
set youtubeUnblock.@section[-1].faking_strategy='pastseq'
set youtubeUnblock.@section[-1].fake_sni_seq_len='1'
set youtubeUnblock.@section[-1].fake_sni_type='default'
set youtubeUnblock.@section[-1].frag='tcp'
set youtubeUnblock.@section[-1].frag_sni_reverse='1'
set youtubeUnblock.@section[-1].frag_sni_faked='0'
set youtubeUnblock.@section[-1].frag_middle_sni='1'
set youtubeUnblock.@section[-1].frag_sni_pos='1'
set youtubeUnblock.@section[-1].seg2delay='0'
set youtubeUnblock.@section[-1].fk_winsize='0'
set youtubeUnblock.@section[-1].synfake='0'
add_list youtubeUnblock.@section[-1].sni_domains=cdn.discordapp.com
add_list youtubeUnblock.@section[-1].sni_domains=canary.discord.com
add_list youtubeUnblock.@section[-1].sni_domains=dis.gd
add_list youtubeUnblock.@section[-1].sni_domains=ptb.discord.com
add_list youtubeUnblock.@section[-1].sni_domains=discord-attachments-uploads-prd.storage.googleapis.com
add_list youtubeUnblock.@section[-1].sni_domains=discord-activities.com
add_list youtubeUnblock.@section[-1].sni_domains=discord.co
add_list youtubeUnblock.@section[-1].sni_domains=discord.com
add_list youtubeUnblock.@section[-1].sni_domains=discord.design
add_list youtubeUnblock.@section[-1].sni_domains=discord.dev
add_list youtubeUnblock.@section[-1].sni_domains=discord.gg
add_list youtubeUnblock.@section[-1].sni_domains=discord.gift
add_list youtubeUnblock.@section[-1].sni_domains=discord.gifts
add_list youtubeUnblock.@section[-1].sni_domains=discord.media
add_list youtubeUnblock.@section[-1].sni_domains=discord.new
add_list youtubeUnblock.@section[-1].sni_domains=discord.store
add_list youtubeUnblock.@section[-1].sni_domains=discord.tools
add_list youtubeUnblock.@section[-1].sni_domains=discordactivities.com
add_list youtubeUnblock.@section[-1].sni_domains=discordapp.com
add_list youtubeUnblock.@section[-1].sni_domains=discordapp.net
add_list youtubeUnblock.@section[-1].sni_domains=media.discordapp.net
add_list youtubeUnblock.@section[-1].sni_domains=images-ext-1.discordapp.net
add_list youtubeUnblock.@section[-1].sni_domains=images-ext-2.discordapp.net
add_list youtubeUnblock.@section[-1].sni_domains=stable.dl2.discordapp.net
add_list youtubeUnblock.@section[-1].sni_domains=discordcdn.com
add_list youtubeUnblock.@section[-1].sni_domains=discordmerch.com
add_list youtubeUnblock.@section[-1].sni_domains=discordpartygames.com
add_list youtubeUnblock.@section[-1].sni_domains=discordsays.com
add_list youtubeUnblock.@section[-1].sni_domains=discordsez.com
add_list youtubeUnblock.@section[-1].sni_domains=discordstatus.com
commit youtubeUnblock
EOF
}


cat << 'EOF' >> /etc/ytub.ipt
# Youtube Unblock
ytub(){
	for ipt in iptables ip6tables; do
        	$ipt -t mangle -N YT_UNBLOCK
	        $ipt -t mangle -A YT_UNBLOCK -p tcp --dport 443 \
        	        -m connbytes --connbytes-dir original --connbytes-mode packets \
                	--connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
	        $ipt -t mangle -A YT_UNBLOCK -p udp \
        	        -m connbytes --connbytes-dir original --connbytes-mode packets \
                	--connbytes 0:8 -j NFQUEUE --queue-num 537 --queue-bypass
	        $ipt -t mangle -A POSTROUTING -j YT_UNBLOCK
        	$ipt -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT
	done
}


do_run(){
	/etc/init.d/youtubeUnblock status > /dev/null 2>&1

	[ $? -eq 0 ] && {
		ytub
	}
}

sleep 20 && do_run &
EOF

uci add firewall include
uci set firewall.@include[-1].path=/etc/ytub.ipt
echo "/etc/ytub.ipt" >> /etc/sysupgrade.conf

sleep 30 && set_config &
