#!/bin/sh

# check soft upgrade
[ -f /etc/.config.lock ] && exit 0


# Check modemmanager modems found

mmcheck(){
	MODEMS=$(mmcli -L)
	[ "$MODEMS" = "No modems were found" ] && {
		. /usr/share/xmmconfig
		for m in stop disable; do
			/etc/init.d/modemmanager ${m}
		done
	} || {
		. /usr/share/modemconfig
	}
}

board="$(cat /tmp/sysinfo/board_name)"

setup_mwan3(){
		[ -x /usr/sbin/mwan3 -a -x /usr/share/mwan3_gen.sh ] && {
			logger -t "$NODE" "Generate config for MWAN3."
			MODEMLEN=$(uci show network | awk '/modem/ && /interface/{len++} END {print len}')
			if  [ "$MODEMLEN" -eq "1" ]; then
				MWAN3_POLICY="default"
			elif [ "$MODEMLEN" -ge "2" ]; then
				MWAN3_POLICY="balanced"
			fi
			/usr/share/mwan3_gen.sh wan -i ${MWAN_IFACES:=modem} -p $MWAN3_POLICY > /etc/config/mwan3
			logger -t "$NODE" "MWAN3: default policy is \"$MWAN3_POLICY\""

			# generate led for MWAN3
			case $board in
				beeline,smartbox-turbo-plus|\
				beeline,smartbox-giga|\
				beeline,smartbox-flash)
					LEDS="-l blue:wan -o red:status"
				;;
				cudy,tr3000-v1)
					LEDS="-l white:status -o red:power"
				;;
				huastlink,hc-g60)
					LEDS="-l blue:status -o green:status"
				;;
				zbtlink,zbt-wg2107|\
				zbtlink,zbt-cpe2801-32m)
					LEDS="-l green:wwan1 green:wwan2"
				;;
				zbtlink,zbt-z8102ax-nand|\
				zbtlink,zbt-z8102ax-nand-all|\
				zbtlink,zbt-z8102ax-emmc)
					LEDS="-l blue:usb-0 blue:usb-1"
				;;
				zbtlink,zbt-z8109ax-nand-all)
					LEDS="-l green:modem1 green:modem2 green:modem3 green:modem4"
				;;
				zbtlink,zbt-wg1608-16m|\
				zbtlink,zbt-wg1608-32m)
					LEDS="-l green:wwan"
				;;
				*) LEDS="false" ;;
			esac
			[ "$LEDS" != "false" -a -x /usr/share/mwan3_led_config.sh ] && {
				/usr/share/mwan3_led_config.sh -i ${MWAN_IFACES:=modem} ${LEDS} > /etc/config/mwan3_led
			} || {
				> /etc/config/mwan3_led
			}

			/etc/init.d/mwan3 restart
		}
}


do_run(){
	mmcheck
	sleep 5
	stuff
	sleep 30
	setup_mwan3
}
	

SLEEP=120
# More arch need random times to initialize
[ -f /etc/openwrt_release ] && {
	. /etc/openwrt_release
	case $DISTRIB_TARGET in
		*mt76x8*|*mt7620*|*ath79*) SLEEP=240 ;;
	esac
}

sleep $SLEEP && do_run &