#!/bin/sh

# check soft upgrade
[ -f /etc/.config.lock ] && exit 0

board="$(cat /tmp/sysinfo/board_name)"
RES=/usr/share/modeminfo/modem.list
SMS_CONFIGURED=0

# ============================================================
# COMMON
# ============================================================

args(){
	echo "$#"
}

# UCI init modeminfo and smstools3
default_setup(){
	uci set modeminfo.@general[0]=general
	uci set modeminfo.@general[0].index='1'
	uci set modeminfo.@general[0].decimail='1'
	uci set smstools3.@sms[0]=sms
	uci set smstools3.@sms[0].decode_utf='1'
	uci set smstools3.@sms[0].storage='temporary'
	uci set smstools3.@sms[0].loglevel='5'
}

log_modem_found(){
	logger -t "$NODE" "Found: $FAMILY (${VID}:${PID}) -> $ifmodemname data: ${DEVICE}"
	[ ${SMSPORT} ] && {
		logger -t "$NODE" "Ports at: /dev/${ATPORT} sms: /dev/${SMSPORT}"
	} || {
		logger -t "$NODE" "Ports at: /dev/${ATPORT}"
	}
}

log_xmm_found(){
	local smsport="${device%?}$((${device: -1}+2))"
	logger -t "$NODE" "Found: $FAMILY (${vid}:${pid}) -> $ifmodemname data: /dev/${device}"
	logger -t "$NODE" "Ports at: /dev/${device} sms: /dev/${smsport}"
}

# SIM error
log_sim_missing(){
	logger -t "$NODE" "WARNING: $ifmodemname SIM is missing or not ready. Disabled:"
	logger -t "$NODE" "WARNING:   - network interface bring up"
	logger -t "$NODE" "WARNING:   - SMS messaging"
	logger -t "$NODE" "WARNING:   - ping alive link"
	logger -t "$NODE" "WARNING: Fix SIM issue and configure manually, or reset to defaults."
}


# ============================================================
# MODEMCONFIG (modemmanager / mmcli)
# ============================================================

stop_services(){
	for svc in "$@"; do
		/etc/init.d/${svc} stop
		/etc/init.d/${svc} disable
	done
}

read_modem_list(){
	MODEMS=$(jsonfilter -s "$(mmcli -L -J)" -e "@['modem-list'][*]" | sort)
}

atinout_cfg_nl678(){
cat << 'EOF' >> /etc/atcommands.user
Demo command "ATI";ATI
NL678 - to NCM(23);AT+GTUSBMODE=23
NL678 - to QMI(22);AT+GTUSBMODE=22
NL678 - to QMI(17);AT+GTUSBMODE=17
NL678 - reboot modem;AT+CFUN=1,1
EOF
}

atinout_cfg_l850(){
cat << 'EOF' >> /etc/atcommands.user
Demo command "ATI";ATI
L850 - to MBIM(7);AT+GTUSBMODE=7
L850 - to NCM(0);AT+GTUSBMODE=0
L850 - reboot modem;AT+CFUN=15
EOF
}

atinout_msg(){
	logger -t "$NODE" "WARNING: Generate atinout commands for change USB-composition"
	logger -t "$NODE" "WARNING: Go to \"Modem\" -> \"AT Commands\" and select modem mode."
	logger -t "$NODE" "WARNING: Select AT-port and put command to modem"
	logger -t "$NODE" "WARNING: For autoconfig reset router to defaults."
}

failed_msg(){
	logger -t "$NODE" "WARNING: But modem is failed with reason: \"${FAILED}\". Functionality is disabled."
	logger -t "$NODE" "WARNING: Eliminate the failure cause and enable check ping,"
	logger -t "$NODE" "WARNING: Network interface and SMS messaging manually"
	logger -t "$NODE" "WARNING: or reset device to defaults, for automatic setup."
}

standby_modems(){
	i=0
	while true; do
		! [ "$MODEMS" ] && {
			read_modem_list
			[ $i -gt 30 ] && { exit 0; }
		} || {
			break
		}
		sleep 4
		i=$(($i+1))
	done
}

get_modem_param(){
	jsonfilter -s "$(mmcli -m ${m} -J)" \
		-e "DEVICE=$['modem']['generic']['device']" \
		-e "PORTS=$['modem']['generic']['ports'][*]" \
		-e "OPERATOR=$['modem']['3gpp']['operator-code']" \
		-e "FAILED=$['modem']['generic']['state-failed-reason']"
}

setup_modeminfo(){
	local port="$1"
	uci add modeminfo modeminfo
	case $port in
		*ttyUSB*|*ttyACM*)
			uci set modeminfo.@modeminfo[-1].device=/dev/${port}
			case $FAMILY in
				*DELL*|*QUALCOMM*) uci set modeminfo.@modeminfo[-1].mmcli_name=1 ;;
			esac
		;;
		*cdc-wdm*)
			uci set modeminfo.@modeminfo[-1].qmi_mode=1
			uci set modeminfo.@modeminfo[-1].qmi_proxy=1
			uci set modeminfo.@modeminfo[-1].device_qmi=/dev/${port}
		;;
	esac
}

setup_smstools3(){
	local port="$1"
	uci set smstools3.$ifmodemname=modem
	uci set smstools3.$ifmodemname.device=/dev/${port}
	[ "$ENABLED" = "1" ] && uci set smstools3.$ifmodemname.enable=1
	SMS_CONFIGURED=1
}

setup_pingcontrol(){
	uci set pingcontrol.$ifmodemname=pingcontrol
	[ "$ENABLED" = "1" ] && uci set pingcontrol.$ifmodemname.enabled='1'
	uci set pingcontrol.$ifmodemname.check_period='60'
	uci set pingcontrol.$ifmodemname.ping_silent='1'
	uci set pingcontrol.$ifmodemname.iface=$ifmodemname
	uci set pingcontrol.$ifmodemname.sw_before_modres='2'
	uci set pingcontrol.$ifmodemname.sw_before_sysres='0'
	uci set pingcontrol.$ifmodemname.testip='dns.yandex'
}

setup_iface(){
	local proto="$1"
	local dev="$2"
	uci set network.$ifmodemname=interface
	uci set network.$ifmodemname.proto=$proto
	uci set network.$ifmodemname.device=$dev
	uci set network.$ifmodemname.apn=$APN
	uci set network.$ifmodemname.metric=${mn}00
	[ "$ENABLED" = "1" ] || uci set network.$ifmodemname.disabled='1'
	uci add_list firewall.@zone[1].network=$ifmodemname
	case $proto in
		modemmanager|qmi) uci set network.$ifmodemname.iptype=ipv4 ;;
		xmm)              uci set network.$ifmodemname.pdp=ipv4 ;;
	esac
}

mmconfig_setup(){
	uci set mmconfig.$ifmodemname=modem
	uci set mmconfig.$ifmodemname.device=$DEVICE
}

iface_mm_bearer(){
	case $VIDPID in
		12d11*) uci set network.$ifmodemname.init_epsbearer=none ;;
		*2cb7010a*)
			uci set network.$ifmodemname.init_epsbearer=none
			atinout_cfg_nl678
			logger -t "$NODE" "WARNING: modem in NCM mode, but will work QMI. Please setup modem mode AT-command"
			atinout_msg
		;;
		*8087095a*)
			atinout_cfg_l850
			logger -t "$NODE" "WARNING: modem in XMM mode, check modem model, if model L850 please setup modem mode AT-command"
			atinout_msg
		;;
		*) uci set network.$ifmodemname.init_epsbearer=default ;;
	esac
}

configure_mm_uci(){
	ARGSLENMODEM=$(args $MODEMS)
	[ $ARGSLENMODEM -eq 0 ] && {
		logger -t "$NODE" "WARNING: modems not found in system"
		return 0
	}
	default_setup
	NOT_SUPPORT_MM=1
	HAS_L850=0
	for m in $MODEMS; do
		mmcli -m ${m} -e
		sleep 5
		eval $(echo $(get_modem_param) | sed -e 's/export//g')
		VID=$(cat ${DEVICE}/idVendor)
		PID=$(cat ${DEVICE}/idProduct)
		VIDPID="${VID}${PID}"
		[ -r ${RES} ] && {
			[ "$VID" -a "$PID" ] && {
				FAMILY=$(awk -F [\;] '/'$VIDPID'/{print toupper($2)}' $RES)
			}
			[ "$FAILED" = "--" ] || failed_msg
		}
		resolve_apn $OPERATOR
		make_ifname
		[ "x${VIDPID}" != "x" ] && {
			case $VIDPID in
				8087095a|2c7c6000|2c7c6026|\
				12864e3c|19d20532|305a1415|\
				0e8d7126|0e8d7127|2cd20001|\
				2cd20004|19d21404|19d21424)
					continue
				;;
				2cb70007)
					HAS_L850=1
					NOT_SUPPORT_MM=0
				;;
				*)
					NOT_SUPPORT_MM=0
				;;
			esac
		} || {
			NOT_SUPPORT_MM=1
		}
		case $FAMILY in
			SIERRA|THALES) ATPORT=$(echo "$PORTS" | awk '{for (i=1; i<=NF; i++) if($i ~ /cdc-wdm/) {print $i; exit}}') ;;
			*) ATPORT=$(echo "$PORTS" | awk '{ for (i=1; i<=NF; i++) { if ($(i+1) == "(at)") { print $i; break; }}}') ;;
		esac

		[ "x${m}" != "x" ] && [ "$NOT_SUPPORT_MM" = "0" ] && {
			[ "$FAILED" = "--" ] && ENABLED=1 || ENABLED=0
		}

		! [ "$ATPORT" = "" ] && {
			setup_modeminfo $ATPORT
			case $ATPORT in
				ttyUSB*)
					SMSPORT=${ATPORT%?}$((${ATPORT: -1}+1))
					setup_smstools3 $SMSPORT
					case $VIDPID in
						2cb70104|2cb70109)
							uci set smstools3.$ifmodemname.net_check='0'
							uci set smstools3.$ifmodemname.sig_check='1'
						;;
					esac
				;;
				ttyACM*)
					SMSPORT=${ATPORT%?}$((${ATPORT: -1}+2))
					setup_smstools3 $SMSPORT
					uci set smstools3.$ifmodemname.net_check='0'
					uci set smstools3.$ifmodemname.sig_check='1'
				;;
			esac
		}

                [ "x${m}" != "x" ] && [ "$NOT_SUPPORT_MM" = "0" ] && {
                        setup_iface modemmanager $DEVICE
                        uci add_list network.$ifmodemname.allowedauth=none
                        uci set network.$ifmodemname.signalrate='10'
                        iface_mm_bearer
                        mmconfig_setup
                        setup_pingcontrol
                        uci add_list firewall.@zone[1].network=$ifmodemname
                        log_modem_found
                        logger -t "$NODE" "APN: ${APN}"
                } || {
                        logger -t "$NODE" "WARNING: modem: ${VID}:${PID} not supported by modemmanager."
                        logger -t "$NODE" "WARNING: Please manualy configure interface."
                }

		mn=$(($mn+1))
		MWAN_IFACES="$MWAN_IFACES $ifmodemname"
		unset ATPORT FAMILY
	done
}

mm_stuff(){
	> /etc/config/mmconfig
	standby_modems
	configure_mm_uci
}


# ============================================================
# XMMCONFIG (Fibocom L850/L860/FM350 via xmm proto)
# ============================================================

xmm_uci_config(){
	APN=internet
	[ "$FAILED" = "--" ] && ENABLED=1 || ENABLED=0
	setup_iface xmm /dev/${device}
	setup_modeminfo $device
	setup_pingcontrol
}

xmm_smstools_uci_config(){
	local smsport="${device%?}$((${device: -1}+2))"
	setup_smstools3 $smsport
	uci set smstools3.$ifmodemname.net_check='0'
	uci set smstools3.$ifmodemname.sig_check='1'
}

check_sim(){
	gcom -d /dev/${device} -s /etc/gcom/setpin.gcom > /dev/null 2>&1 && FAILED="--" || FAILED=OK
}

get_tty_vidpid(){
	local dev_name="$1"
	vid="" pid="" interface=""
	[ -e "/sys/class/tty/${dev_name}" ] || return 1
	local tty_path; tty_path=$(readlink -f "/sys/class/tty/${dev_name}" 2>/dev/null)
	local cur="$tty_path" iface_path=""
	while [ -n "$cur" ] && [ "$cur" != "/" ]; do
		[ -f "${cur}/bInterfaceNumber" ] && { iface_path="$cur"; break; }
		cur=$(dirname "$cur")
	done
	[ -n "$iface_path" ] || return 1
	local usb_path; usb_path=$(dirname "$iface_path")
	while [ -n "$usb_path" ] && [ "$usb_path" != "/" ]; do
		[ -f "${usb_path}/idVendor" ] && [ -f "${usb_path}/idProduct" ] && break
		usb_path=$(dirname "$usb_path")
	done
	[ -n "$usb_path" ] && [ "$usb_path" != "/" ] || return 1
	vid=$(cat "${usb_path}/idVendor" 2>/dev/null)
	pid=$(cat "${usb_path}/idProduct" 2>/dev/null)
	interface=$(cat "${iface_path}/bInterfaceNumber" 2>/dev/null)
	return 0
}

resolve_apn(){
	local plmn="$1"
	case $plmn in
		25001) APN=internet.mts.ru ;;
		25011) APN=internet.yota ;;
		25020) APN=internet.tele2.ru ;;
		25099) APN=internet.beeline.ru ;;
		*)     APN=internet ;;
	esac
}

get_usb_info(){
	device="$1"
	get_tty_vidpid "$device" || return 1
	case ${vid}${pid} in
		8087095a)
			case $interface in
				00)
					FAMILY="Fibocom L850/L860 NCM Modem"
					make_ifname
					mn=$((mn+1))
					MWAN_IFACES="$MWAN_IFACES $ifmodemname"
					check_sim
					xmm_uci_config
					xmm_smstools_uci_config
					log_xmm_found
				;;
			esac
		;;
		0e8d7126)
			FAMILY="Fibocom FM350 NCM Modem"
			case $interface in
				04)
					make_ifname
					mn=$((mn+1))
					MWAN_IFACES="$MWAN_IFACES $ifmodemname"
					check_sim
					xmm_uci_config
					log_xmm_found
				;;
			esac
		;;
		0e8d7127)
			FAMILY="Fibocom FM350 NCM Modem"
			case $interface in
				06)
					make_ifname
					mn=$((mn+1))
					MWAN_IFACES="$MWAN_IFACES $ifmodemname"
					check_sim
					xmm_uci_config
					log_xmm_found
				;;
			esac
		;;
	esac
	return 0
}

xmm_stuff(){
	default_setup
	found_devices=0
	for dev_base in ttyUSB ttyACM; do
		dev_num=0
		while true; do
			dev="/dev/${dev_base}${dev_num}"
			if [ -e "$dev" ]; then
				device_name="${dev_base}${dev_num}"
				if get_usb_info "$device_name"; then
					found_devices=$((found_devices + 1))
				fi
				dev_num=$((dev_num + 1))
			else
				if [ $dev_num -eq 0 ]; then
					for alt_dev in "/dev/${dev_base}"*; do
						if [ -e "$alt_dev" ] && [ "$alt_dev" != "/dev/${dev_base}*" ]; then
							device_name=$(basename "$alt_dev2")
							if get_usb_info "$device_name"; then
								found_devices=$((found_devices + 1))
							fi
						fi
					done
				fi
				break
			fi
		done
	done
}


# ============================================================
# QMICONFIG (uqmi / QMI proto b4com only)
# ============================================================

check_mm(){
	[ -x /usr/bin/mmcli ] && {
		STATUS=$(/etc/init.d/modemmanager status > /dev/null 2>&1 && echo $?)
		case $STATUS in
			0)
				stop_services modemmanager
			;;
		esac
	}
}

get_at_port(){
	PORTS=$(ls $(readlink -f /sys/class/usbmisc/${d}/../../../)/*:*/bInterfaceNumber)
	for i in $PORTS; do
		BNUM=$(cat $i)
		case $BNUM in
			$IFACE_NUM)
				ATPORT=$(ls -1 ${i%/*}/ | grep tty)
				SMSPORT=${ATPORT%?}$((${ATPORT: -1}+1))
			;;
		esac
	done
}

qmi_ports(){
	FAMILY=$1
	case $FAMILY in
		QUECTEL) IFACE_NUM=02 ;;
		DELL) IFACE_NUM=02 ;;
		MEIGLINK) IFACE_NUM=01 ;;
		FIBOCOM)
			case $PID in
				104) IFACE_NUM=01 ;;
				109) IFACE_NUM=00 ;;
			esac
		;;
		*)
			logger -t "$NODE" "Modem family not supported"
			return 1
		;;
	esac
}

qmi_device(){
	case $board in
		b4com,mcr100|b4com,mcr200)
			# accept
		;;
		*)
			logger -t "$NODE" "QMI device detection skipped: not a b4com board"
			return 0
		;;
	esac
	
	CDC_WDM_DEV=$(ls /sys/class/usbmisc/)
	ARGSLENMODEM=$(args $CDC_WDM_DEV)
	[ "$ARGSLENMODEM" -eq "0" ] && {
		logger -t "$NODE" "WARNING: modems not found in system"
		return 1
	} || {
		default_setup
	}
	for d in $CDC_WDM_DEV; do
		make_ifname
		case $d in
			cdc-wdm*)
				ls $(readlink -f /sys/class/usbmisc/${d}/../../driver/module/drivers/) | grep -i qmi > /dev/null 2>&1
				case $? in
					0)
						VID=$(cat $(readlink -f /sys/class/usbmisc/${d}/../../../idVendor))
						PID=$(cat $(readlink -f /sys/class/usbmisc/${d}/../../../idProduct))
						mn=$(($mn+1))
						DEVICE=/dev/${d}
						[ -r ${RES} ] && {
							[ "$VID" -a "$PID" ] && {
								FAMILY=$(awk -F [\;] '/'${VID}${PID}'/{print toupper($2)}' $RES)
								qmi_ports $FAMILY
								get_at_port
								log_modem_found
								SIM=$(uqmi -d ${DEVICE} --uim-get-sim-state | jsonfilter -e '@["card_application_state"]')
								[ $SIM = "ready" ] || log_sim_missing
								eval $(uqmi -d ${DEVICE} --get-serving-system | jsonfilter \
									-e "MCC=$['plmn_mcc']" \
									-e "MNC=$['plmn_mnc']")
								resolve_apn "${MCC}${MNC}"
								[ "$SIM" = "ready" ] && ENABLED=1 || ENABLED=0
								setup_iface qmi $DEVICE
								setup_modeminfo $ATPORT
								setup_pingcontrol
								setup_smstools3 $SMSPORT
							}
						}
						MWAN_IFACES="$MWAN_IFACES $ifmodemname"
						unset ATPORT FAMILY VID PID
						continue 2
					;;
					*) logger -t "$NODE" "Device /dev/${d} is not QMI. Skip." ;;
				esac
			;;
		esac
	done
}

qmi_stuff(){
	[ -x /sbin/uqmi ] || {
		logger -t "$NODE" "WARNING: UQMI not found in system!"
		return 1
	}
	check_mm
	sleep 10
	qmi_device
}


# ============================================================
# MWAN3
# ============================================================

setup_mwan3(){
	[ -x /usr/sbin/mwan3 -a -x /usr/share/mwan3_gen.sh ] && {
		logger -t "$NODE" "Generate config for MWAN3."
		MODEMLEN=$(uci show network | awk '/modem/ && /interface/{len++} END {print len}')
		if [ "$MODEMLEN" -eq "1" ]; then
			MWAN3_POLICY="default"
		elif [ "$MODEMLEN" -ge "2" ]; then
			MWAN3_POLICY="balanced"
		fi
		case $board in
			beeline,smartbox-turbo-plus|\
			beeline,smartbox-giga|\
			beeline,smartbox-flash)
				LEDS="-l blue:wan -o red:status"
			;;
			cudy,tr3000-v1)
				LEDS="-l white:status -o red:power"
			;;
			huastlink,hc-g60)
				LEDS="-l blue:status -o green:status"
			;;
			huastlink,hc-g60-v1|\
			huastlink,hc-g80|\
			zbtlink,zbt-wg1608-16m|\
			zbtlink,zbt-wg1608-32m)
				LEDS="-l green:wwan"
			;;
			netis,n6)
				LEDS="-l green:indicator"
			;;
			zbtlink,zbt-wg2107)
				LEDS="-l green:wwan1 green:wwan2"
			;;
			zbtlink,zbt-cpe2801-32m)
				LEDS="-l green:wwan1 green:wwan2"
				PORT_WAN=0
			;;
			zbtlink,zbt-z8102ax-nand-64m|\
			zbtlink,zbt-z8102ax-nand-all|\
			zbtlink,zbt-z8102ax-v2|\
			zbtlink,zbt-z8102ax-emmc)
				LEDS="-l blue:usb-0 blue:usb-1"
			;;
			zbtlink,zbt-z8109ax-nand-64m|\
			zbtlink,zbt-z8109ax-nand-128m|\
			zbtlink,zbt-z8109ax-nand-all)
				LEDS="-l green:modem1 green:modem2 green:modem3 green:modem4"
			;;
			*) LEDS="false" ;;
		esac
		[ "$LEDS" != "false" -a -x /usr/share/mwan3_led_config.sh ] && {
			/usr/share/mwan3_led_config.sh -i ${MWAN_IFACES:=modem} ${LEDS} > /etc/config/mwan3_led
		} || {
			> /etc/config/mwan3_led
		}
		[ "$PORT_WAN" = "0" ] || MWAN_IFACES="wan $MWAN_IFACES"
		/usr/share/mwan3_gen.sh -i ${MWAN_IFACES:=modem} -p $MWAN3_POLICY > /etc/config/mwan3
		logger -t "$NODE" "MWAN3: default policy is \"$MWAN3_POLICY\". Restart service to take effect."
		/etc/init.d/mwan3 restart
	}
}


# ============================================================
# DETECT — calc modems
# ============================================================

count_xmm_modems(){
	XMM_COUNT=0
	for dev_base in ttyUSB ttyACM; do
		dev_num=0
		while true; do
			[ -e "/dev/${dev_base}${dev_num}" ] || break
			if get_tty_vidpid "${dev_base}${dev_num}"; then
				case ${vid}${pid} in
					8087095a) [ "$interface" = "00" ] && XMM_COUNT=$((XMM_COUNT+1)) ;;
					0e8d7126) [ "$interface" = "04" ] && XMM_COUNT=$((XMM_COUNT+1)) ;;
					0e8d7127) [ "$interface" = "06" ] && XMM_COUNT=$((XMM_COUNT+1)) ;;
				esac
			fi
			dev_num=$((dev_num+1))
		done
	done
}

detect_modems(){
	MM_LIST=$(mmcli -L 2>/dev/null)
	if [ "$MM_LIST" = "No modems were found" ] || [ -z "$MM_LIST" ]; then
		MM_COUNT=0
	else
		MM_COUNT=$(echo "$MM_LIST" | grep -c '/Modem/')
	fi

	count_xmm_modems

	TOTAL_MODEMS=$((MM_COUNT + XMM_COUNT))
	case $TOTAL_MODEMS in
		0) logger -t "$NODE" "No modems were found" ;;
		*) logger -t "$NODE" "Detected $TOTAL_MODEMS modem(s)" ;;
	esac
}

make_ifname(){
	[ "$TOTAL_MODEMS" -eq "1" ] && ifmodemname=modem || ifmodemname=modem${mn}
}


# ============================================================
# MAIN
# ============================================================

NODE=modemconfig

do_run(){
	MWAN_IFACES=""
	mn=1
	SMS_CONFIGURED=0

	case $board in
		b4com,mcr100|b4com,mcr200)
			TOTAL_MODEMS=$(ls /sys/class/usbmisc/cdc-wdm* 2>/dev/null | wc -l)
			logger -t "$NODE" "Detected $TOTAL_MODEMS QMI modem(s) on b4com board"
			qmi_stuff
		;;
		*)
			detect_modems

			[ "$MM_COUNT" -gt "0" ] && {
				mm_stuff
			} || {
				stop_services modemmanager
			}

			[ "$XMM_COUNT" -gt "0" ] && xmm_stuff
		;;
	esac

	sleep 35
	uci commit
	reload_config

	if [ "$SMS_CONFIGURED" -eq 0 ]; then
		stop_services smstools3 luci-sms
		logger -t "$NODE" "WARNING: No SMS ports configured"
		logger -t "$NODE" "WARNING: SMS messaging functionality disabled."
		logger -t "$NODE" "WARNING: Please manually configure service."
	fi

	[ "$HAS_L850" != "1" ] && [ -x /etc/init.d/fixmodem ] && /etc/init.d/fixmodem disable

	if [ "$mn" -eq "1" ]; then
		logger -t "$NODE" "WARNING: Any installed modems not supported by autoconfiguration."
		logger -t "$NODE" "WARNING: Mobile services is stopped."
		logger -t "$NODE" "WARNING: Please manually configure it."
		stop_services smstools3 luci-sms modemmanager
		atinout_cfg_l850
		atinout_cfg_nl678
		atinout_msg
	else
		logger -t "$NODE" "Modem interface(s) setup complete."
	fi

	setup_mwan3
}

SLEEP=120
[ -f /etc/openwrt_release ] && {
	. /etc/openwrt_release
	case $DISTRIB_TARGET in
		*mt76x8*|*mt7620*|*ath79*) SLEEP=240 ;;
	esac
}

sleep $SLEEP && do_run &
