#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

if ! [ -x /usr/sbin/wpad -o -x /usr/sbin/hostapd ]; then
	exit 0
fi

MACHINE=$(awk '{print $2}' /sys/firmware/devicetree/base/model)
SUFFIX=$(awk -F [:] '{print toupper($4$5$6)}' /sys/class/net/eth0/address)
CC=RU

config_wifi(){
	uci -q set wireless.radio${r}.country=$CC
	uci -q set wireless.default_radio${r}.ssid=${MACHINE:=WIFI}_${BAND}_${SUFFIX:=$r}
	uci -q delete wireless.radio${r}.disabled='1'
}

# 5 radios enough devices :)
enable_wifi(){
	for r in $(seq 0 5); do
		BAND=$(uci -q get wireless.radio${r}.band)
		case $BAND in
			2g)
				config_wifi
				uci -q set wireless.radio${r}.noscan='1'
			;;
			5g|6g)
				config_wifi
			;;
		esac
		unset BAND
	done

	uci -q commit wireless
	wifi
}

# More chips slowly start radio
sleep 30 && enable_wifi &
