#!/bin/sh

board="$(cat /tmp/sysinfo/board_name)"

remove_unused_init(){
	[ -x /etc/init.d/modem_switch ] && {
		/etc/init.d/modem_switch disable
		rm -f /etc/init.d/modem_switch
	}
}


fixmodems(){
cat << EOF > /etc/init.d/fixmodem
#!/bin/sh /etc/rc.common
#
START=50

start(){
	for g in $@; do
		echo 0 > /sys/class/gpio/\${g}/value
		sleep 3
		echo 1 > /sys/class/gpio/\${g}/value
	done
}
EOF
chmod +x /etc/init.d/fixmodem
/etc/init.d/fixmodem enable
/etc/init.d/fixmodem start
}

restart_modem(){
        i=1
        for g in $@; do
                uci add luci command
                uci set luci.@command[-1].name="Restart Modem ${i} on GPIO: ${g}"
                uci set luci.@command[-1].command="/usr/share/pwr ${g}"
                i=$(($i+1))
        done
cat << EOF > /usr/share/pwr
#!/bin/sh
for s in 0 1; do
        echo \${s} > /sys/class/gpio/${g}/value
        sleep 3
        echo \${s} > /sys/class/gpio/${g}/value
done

[ -x /etc/init.d/smtools3 ] && {
	sleep 10 && /etc/init.d/smstools3 restart &
}
EOF
chmod +x /usr/share/pwr
}


mwan3_conf(){
	case $1 in
		1m)
			[ -f /usr/share/config/mwan3_1m ] && {
				cp /usr/share/config/mwan3_1m /etc/config/mwan3
			}
		;;
		2m)
			[ -f /usr/share/config/mwan3_2m ] && {
				cp /usr/share/config/mwan3_2m /etc/config/mwan3
			}
		;;
	esac

cat << 'EOF' >> /etc/mwan3.user
JSON=$(ifstatus $INTERFACE)

get_vars(){
        jsonfilter -s "$JSON" \
                -e "METRIC=@['metric']" \
                -e "GW=@['route'][*]['nexthop']"
}

eval $(get_vars)


case $ACTION in
	connected) ifmetric $DEVICE $METRIC ;;
	disconnected) ifmetric $DEVICE $(($METRIC+1000)) ;;
esac
EOF
}

MACHINE=$(awk '{print $2}' /sys/firmware/devicetree/base/model)

case $board in
	zbtlink,zbt-z8102ax-nand|\
	zbtlink,zbt-z8102ax-emmc)
		restart_modem 5g1 5g2
		fixmodems 5g1 5g2
		mwan3_conf 2m
	;;
	zbtlink,zbt-wg2107)
		restart_modem modem1pwr modem2pwr
		fixmodems modem1pwr modem2pwr
		mwan3_conf 2m
	;;
	zbtlink,zbt-cpe2801-16m|\
	zbtlink,zbt-cpe2801-32m)
		restart_modem mpcie1 mcpie2
		fixmodems mpcie1 mcpie2
		mwan3_conf 2m
	;;
	zbtlink,zbt-we826-t3-16m|\
	zbtlink,zbt-we826-t3-32m)
		restart_modem modem
		fixmodems modem
		mwan3_conf 1m
	;;
	zbtlink,zbt-wg1602-16m|\
	zbtlink,zbt-wg1602-v04-16m|\
	zbtlink,zbt-wg1602-v04-32m)
		restart_modem 4g1-pwr 4g2-pwr
		fixmodems 4g1-pwr 4g2-pwr
		mwan3_conf 2m
	;;
	irz,ru-41u|\
	irz,ru-41l)
		restart_modem m0reset m1reset
		fixmodems m0reset m1reset
		mwan3_conf 2m
	;;
	mikrotik,routerboard-m33g)
		mwan3_conf 2m
	;;
	# fix LED
	zbtlink,zbt-we826-16m)
		uci del system.led_wifi_led.mode
		uci add_list system.led_wifi_led.mode='link'
		uci add_list system.led_wifi_led.mode='tx'
		uci add_list system.led_wifi_led.mode='rx'
		uci set system.led_wifi_led.dev='phy0-ap0'
		mwan3_conf 1m
	;;
	*)
		mwan3_conf 1m
	;;
esac

! [ "$board" = "netgear,lbr20" ] && {
	remove_unused_init
}

uci batch << EOF
set system.@system[-1].zonename='Europe/Moscow'
set system.@system[-1].timezone='MSK-3'
set system.@system[-1].hostname=$MACHINE
commit system
EOF
