#!/bin/sh

MODULE=/etc/modules.d/33-nat64
IP4PREFIX=172.16.250.0
IP6PREFIX=64:ff9b::

cat << EOF > $MODULE
nat64 ipv4_prefix=${IP4PREFIX}/24 ipv6_prefix=${IP6PREFIX}/96
EOF

rmmod nat64
insmod $(cat $MODULE)

[ -f /etc/.config.lock ] && exit 0

uci batch << EOF
set network.nat64=interface
set network.nat64.proto='none'
set network.nat64.device='nat64'
set network.nat64.force_link='1'
set network.nat64.defaultroute='0'
set network.nat64.delegate='0'
set network.nat64.disabled='1'
add_list firewall.@zone[0].network='nat64'
add network route
set network.@route[-1].interface='nat64'
set network.@route[-1].target=${IP4PREFIX}/24
set network.@route[-1].disabled='1'
add network route6
set network.@route6[-1].interface='nat64'
set network.@route6[-1].target=${IP6PREFIX}/96
set network.@route6[-1].disabled='1'
set totd.@totd[0].forwarder='127.0.0.1#5353'
set totd.@totd[0].prefix='64:ff9b::'
EOF
uci commit network
uci commit firewall
uci commit totd
