#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

cat << 'EOF' > /etc/mptcpd/mptcpd.conf
[core]
log=syslog
plugin-dir=/usr/lib/mptcpd
path-manager=addr_adv
addr-flags=subflow,fullmesh
notify-flags=existing,skip_link_local,skip_loopback,check_route
load-plugins=addr_adv,sspi
EOF

