#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

# genetate ula prefix from default ll address
ula=$(awk -F [:] '{print "fc00:" tolower($3$4) ":" tolower($5$6) "::/48"}' /sys/class/net/eth0/address)
# config network
uci batch << EOF
delete network.wan6
set network.azp=interface
set network.azp.device='azp0'
set network.azp.proto='none'
set network.lan.ip6assign='64'
set network.globals.ula_prefix=$ula
commit network
EOF

# fix error ifup L850 modem
cat << 'EOF' > /etc/hotplug.d/iface/01-mm-error
#!/bin/sh

error(){
        ERROR_CODE=$(ifstatus $1 | jsonfilter -e '@["errors"][*]["code"]')
        [ "$ERROR_CODE" = "MM_3GPP_OPERATOR_REGISTRATION_FAILED" ] && {
                ifup $1
        }
}

[ "$ACTION" = "ifup-failed" ] && {
        sleep 10 && error $INTERFACE &
}
EOF
