#!/bin/sh

FILE=/etc/hotplug.d/usb/90-ttyrename

cat << 'EOF' > $FILE
#!/bin/sh

case $ACTION in
	bind)
		case ${DRIVER} in
			*option*)
				TTYNAME=USB5
				DEVTTY=$(ls /sys/$DEVPATH/ | grep tty)
				DEVNUM=$(ls -1 /dev/tty${TTYNAME}* | wc -l)
				ln -s /dev/${DEVTTY} /dev/tty${TTYNAME}${DEVNUM}
			;;
			*cdc_acm*)
				TTYNAME=ACM5
				DEVTTY=$(ls /sys/$DEVPATH/tty/ | grep tty)
				if [ $DEVTTY ]; then
					DEVNUM=$(ls -1 /dev/ | grep ${TTYNAME} | wc -l)
					ln -s /dev/${DEVTTY} /dev/tty${TTYNAME}${DEVNUM}
				fi
			;;
		esac
	;;
	remove)
		case ${DRIVER} in
			*option*) TTYNAME=USB5 ;;
			*cdc_acm*) TTYNAME=ACM5 ;;
		esac
		rm -f /dev/tty${TTYNAME}*
	;;
esac
EOF
