#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

CONFIG_AZP=/etc/openvpn/azp.ovpn

uci batch << EOF
set openvpn.azp=openvpn
set openvpn.azp.config=$CONFIG_AZP
set openvpn.azp.enabled='0'
delete openvpn.custom_config
delete openvpn.sample_server
delete openvpn.sample_client
EOF


cat << 'EOF' > $CONFIG_AZP
##############################################
# ProstoVPN.AntiZapret                       #
# http://antizapret.prostovpn.org            #
##############################################

##### NOTE TO LINUX USERS #####
# OpenVPN does not handle DNS on Linux.
# This also applies to ROUTERS.
#
# You have two workarounds:
# 1. Configure OpenVPN connection using NetworkManager.
#    This is preferrable method.
# 2. Uncomment the lines below
#    For Debian, Ubuntu and derivatives:
#
# script-security 2
# up /etc/openvpn/update-resolv-conf
# down /etc/openvpn/update-resolv-conf
#
#    For Fedora:
#
# script-security 2
# up /usr/share/doc/openvpn/contrib/pull-resolv-conf/client.up
# down /usr/share/doc/openvpn/contrib/pull-resolv-conf/client.down
#
#
# For routers, contact your router manufacturer, or visit
# https://ntc.party/c/antizapret-prostovpn-org/5
#
###############################

nobind
client

remote vpn.antizapret.prostovpn.org

remote-cert-tls server

dev azp0
dev-type tun
proto tcp
cipher AES-128-CBC
#setenv opt data-ciphers AES-128-GCM:AES-256-GCM:AES-128-CBC

resolv-retry infinite
persist-key
persist-tun

#setenv FRIENDLY_NAME "AntiZapret VPN TCP"

# Allow weak (MD5) hash in certificate signature.
# COMMENT OR REMOVE this line if you have error such as:
#
# Failed to set restricted TLS cipher list: DEFAULT:@SECLEVEL=0
#
setenv opt tls-cipher "DEFAULT:@SECLEVEL=0"

# Keys
<ca>
-----BEGIN CERTIFICATE-----
MIIDVDCCAjygAwIBAgIURU65u6E+emGuYHg2w1kXS2fUsP0wDQYJKoZIhvcNAQEL
BQAwGTEXMBUGA1UEAwwOQW50aVphcHJldCBDQTIwHhcNMjMwMzEyMDgyMTExWhcN
MzMwMzA5MDgyMTExWjAZMRcwFQYDVQQDDA5BbnRpWmFwcmV0IENBMjCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAIesu3leAXZve0Cuuww0JT+Q2BUGDYjW
35yyEJexDmVdaRswZD7U5jYcqz3CyuAQUlSGFf5h/oDZTLnSUfmTuzNehkUlEFPE
V8JN3A3ZjG6CPXlkYFjjOcMosQxyLm6t7t18OrJfW4tdHCsX7FbvcM3koWPa6I0N
47nERlYEaaDYvKeP2WyKOh6CvalyL0PJU/a04BbzIR1CznyCwPfstJ2Pwc4r7UGg
agWY/WxAtJUchhatED7CDPuNzRmJSGH/PLeAZLwmOXVZkUUyrRudUqjYrftPW9ok
Kz7C2dztWTnAhES3VVHTrvOQFHVdgY5YAZjbF9rxc4wi0JCwWm1csxECAwEAAaOB
kzCBkDAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBSIVFSaVM34YEmnIHGpwVtuJXyF
qDBUBgNVHSMETTBLgBSIVFSaVM34YEmnIHGpwVtuJXyFqKEdpBswGTEXMBUGA1UE
AwwOQW50aVphcHJldCBDQTKCFEVOubuhPnphrmB4NsNZF0tn1LD9MAsGA1UdDwQE
AwIBBjANBgkqhkiG9w0BAQsFAAOCAQEAU78Us7Dx0RzkQ5j33VakarFJH4uIeIXS
h9MBQSaPxuSMKu8ou+TKnnLWogqNtDbbdBd5+C1guB2JWJ5vL6uLwdur1L+K2VJ7
AQW61qXBzRW0xYqyjGdHAHMZlvBgjWiYWNRHfyOrL/001pbXdlEmCLM/bEcxof5f
THlDgo5hdeBEu8UCS8ownb+onW0+hvXegw7xOj5vnc2Y5atfwL181lK18AGR0KIy
7Z08ifUG/1AMHE3z18UdnGdLGFaRc4ZNjz8QRsGu3GIAe9dZLiZBqrb4V3LWw9Yu
W8Jhygq7qQgntCDOfixM/7KeWNBgwf43jPMDoBbfhLQJWimq6EuAgw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEKzCCA5SgAwIBAgIJAJuJfmHjR7wuMA0GCSqGSIb3DQEBBQUAMIHAMQswCQYD
VQQGEwJSVTELMAkGA1UECBMCUlUxETAPBgNVBAcTCEludGVybmV0MRUwEwYDVQQK
EwxQcm9zdG9WUE4ucnUxEzARBgNVBAsTCkFudGlaYXByZXQxIDAeBgNVBAMTF1By
b3N0b1ZQTi5BbnRpWmFwcmV0IENBMSAwHgYDVQQpExdQcm9zdG9WUE4uQW50aVph
cHJldCBDQTEhMB8GCSqGSIb3DQEJARYSYWRtaW5AcHJvc3RvdnBuLnJ1MB4XDTEz
MDMyMjEzNDYzMFoXDTIzMDMyMDEzNDYzMFowgcAxCzAJBgNVBAYTAlJVMQswCQYD
VQQIEwJSVTERMA8GA1UEBxMISW50ZXJuZXQxFTATBgNVBAoTDFByb3N0b1ZQTi5y
dTETMBEGA1UECxMKQW50aVphcHJldDEgMB4GA1UEAxMXUHJvc3RvVlBOLkFudGla
YXByZXQgQ0ExIDAeBgNVBCkTF1Byb3N0b1ZQTi5BbnRpWmFwcmV0IENBMSEwHwYJ
KoZIhvcNAQkBFhJhZG1pbkBwcm9zdG92cG4ucnUwgZ8wDQYJKoZIhvcNAQEBBQAD
gY0AMIGJAoGBALD87/nnrvAvOv3GDSpmYUgdDy34rVjFtlKmigu24qyFKp4dGlfx
x+JWurQcxzMZSBUajNgIqwb0ltJgK2fYtnIMZwRFX3aOdm7n6U0ec0rEotWx09ZY
15dGLwy3KYIRlom+CKjc9I8h95peI9CRBeKnIPLk76figBos8qU/jk9bAgMBAAGj
ggEpMIIBJTAdBgNVHQ4EFgQUa1zT3sc+JvPmjh9Cq3pVA0m++GwwgfUGA1UdIwSB
7TCB6oAUa1zT3sc+JvPmjh9Cq3pVA0m++GyhgcakgcMwgcAxCzAJBgNVBAYTAlJV
MQswCQYDVQQIEwJSVTERMA8GA1UEBxMISW50ZXJuZXQxFTATBgNVBAoTDFByb3N0
b1ZQTi5ydTETMBEGA1UECxMKQW50aVphcHJldDEgMB4GA1UEAxMXUHJvc3RvVlBO
LkFudGlaYXByZXQgQ0ExIDAeBgNVBCkTF1Byb3N0b1ZQTi5BbnRpWmFwcmV0IENB
MSEwHwYJKoZIhvcNAQkBFhJhZG1pbkBwcm9zdG92cG4ucnWCCQCbiX5h40e8LjAM
BgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAKMzBQ9qWk+eAFz4WrcIsVqA
Mgh9Vu1BTvDLH0vKJkFdL23yH7DHnXPs8UqkLHQtzAswaFAMNrINJAYP10MpQx8K
M0orrNKF/Jv+jnuu0yq16UoBFxJCKsdmetoCZz1HuK+5Sop140BRBu1bNOdQ9uNK
Ou4wOSFpotTP2gVFxctw
-----END CERTIFICATE-----
</ca>

<cert>
-----BEGIN CERTIFICATE-----
MIIDbTCCAlWgAwIBAgIRAKJHN43vTRTgP+kn8Ky94UQwDQYJKoZIhvcNAQELBQAw
GTEXMBUGA1UEAwwOQW50aVphcHJldCBDQTIwHhcNMjMwMzEyMDgyMTI3WhcNMzMw
MzA5MDgyMTI3WjAjMSEwHwYDVQQDDBhhbnRpemFwcmV0LWNsaWVudC1zaGFyZWQw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvtMxhTLjfJgdBI2PS5Kj6
ORHL507jk76TO4HkHogEmWWkw0lQENPAiQxozhhswal61+yj70J9bvU2qMKaxseK
rGZ8/kYM/ZNMvQcp2L3iPfj1ADR5I197BYQVwhUc65EBmQzRZtdN2vNBJNi9Cag7
Hp9GZ5waPLiUxna1s8FV3h39wom1qk3S+hWZhFk5bfVpExKLs+7FOz7lhJqPd9eV
p/bK5hAVbsKe029EMdS1uvDte3bCnlnSjDnP+2ekzrPrPk3t94POeqTvfaEvBBKC
CxUB4156K2SxvtuQVauetCZY+wSTfaL86EDklo+91b9NHT9wrTiYz99r4GLFSZI3
AgMBAAGjgaUwgaIwCQYDVR0TBAIwADAdBgNVHQ4EFgQUKkI68+tGkEuE9Ccdoq16
vnMqD2gwVAYDVR0jBE0wS4AUiFRUmlTN+GBJpyBxqcFbbiV8haihHaQbMBkxFzAV
BgNVBAMMDkFudGlaYXByZXQgQ0EyghRFTrm7oT56Ya5geDbDWRdLZ9Sw/TATBgNV
HSUEDDAKBggrBgEFBQcDAjALBgNVHQ8EBAMCB4AwDQYJKoZIhvcNAQELBQADggEB
AGikbTEkjoLwwhTJOOqMFGS1wPjvygQ3bePMDcZ40HM6AeN/a/I5NTYJ1je7OeSO
+AYGHvz5iTcW+Zx59DJ4esY9/3BbM+u3WVTm+VqbWSGII/EW4q9OMDelZns2ZhQ1
wdk40n+kE+zo8xKavu7fnYAmHeTn2f3MyNyEi3mPfPhL5F5Im8HgaDMxxKjrNmlr
lo7Fod1OAENIXl1txK2YvtqvsZIi+bVtpMAvo8EgMdHW76WKbidIpojEUA85LU63
RBVmY/jVRYeZyajwzb+wq4ozA2ge2+lgUpGqWlZg0LbSVsvCNyzHqBl1NNysN4pK
ByzVZCS7OXF6uAKg2T2TFIw=
-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvtMxhTLjfJgdB
I2PS5Kj6ORHL507jk76TO4HkHogEmWWkw0lQENPAiQxozhhswal61+yj70J9bvU2
qMKaxseKrGZ8/kYM/ZNMvQcp2L3iPfj1ADR5I197BYQVwhUc65EBmQzRZtdN2vNB
JNi9Cag7Hp9GZ5waPLiUxna1s8FV3h39wom1qk3S+hWZhFk5bfVpExKLs+7FOz7l
hJqPd9eVp/bK5hAVbsKe029EMdS1uvDte3bCnlnSjDnP+2ekzrPrPk3t94POeqTv
faEvBBKCCxUB4156K2SxvtuQVauetCZY+wSTfaL86EDklo+91b9NHT9wrTiYz99r
4GLFSZI3AgMBAAECggEADoLTiEuiTwegfMAz+9RXoka5Ugo56TCoAhfdi937pMmY
a+mW8e5Z1qJa7ILs4HqECTmw+P8HEj3qMYfxfn/hNfI0CqmjVmpQ0nsgDtQwJnGw
0Gcibki+F3ZmqLddMATCdovR0693I55sDZrB7abRBoTqaZGgAki2g876OdptIq6w
6T6zvM/gNyhyFsKBJKhE40dxVBVvL/xGopIbcbtjqsLgJQYeM72baKpAxCyYQu98
scDWrMPsLW2Rb6y+35VfLHMG3krB9R4KqbS3SftiIV+nYrRyZuZ/dadB4Yk5ASQr
w2qge7ivzH16ZsMCR583b2ZRHJfDJ2ZHd4E60VOcqQKBgQDXVQQ1p2R94ryrbzsE
dqTCsF5uVmdBJddlKzuB5orTMzUJ8T4mK7NlG7ptHpPv7HSJ250b1+XC5+7Fn3y1
ZEHiNOp+XpFtv2tUaEwsDuM5KKws2DIBkdxF/QjgK7jh+o5IEgZ6mN53ebzvJILM
IvQravTJJ0yTpRRL26wOUtqADwKBgQDQ4+50bjYPjXNYp71hkir19w1kEisbhev9
6vef/KCcs01+S8wJ5KH7nb4Ox2fn+jdzSPII05BposIFhkLWp+6GR85qZgHTkFlG
dzBGevq+x3eDYK9Ay8sMEDjajewat13BWbC9/X+3RPWYEiq/uGs8Tkr3IWShHQDZ
vW+CCh8jWQKBgQCDv46dzVdc9nd9ZMb1SiowvHxqgg8W+zI4wiTcq9PQuQoAlUvz
StWuTTLZRNY6+6+qEWak/ImloQakf5pr2XW+E6ZNv0q3nWDr+gxxAILiHBKMNZMT
Bs2BPPpLPjUWfpjDW9P++r1S2HdS0kH86H4AeqZe1N6zj1NFvpgdA3CQ3QKBgGix
M/uqmPGmhR7zwti590obLdzvticvMZ2rO7w1UxH2U2pu9q4mpoCDCJRDoHIFV/Ex
qAyAbCplZjR6m9kVhVhLeMqeoV+1QuksJ0fLrwwa0G1J8cvZ18QOBVCUPLcPG7Ai
EZDHElF6AFTdFgvMlAI/gxbk55hP/vMiHFbiV8TRAoGAImVygtTH/b+zH3WHLNy8
3EbwjLTsoK+rZh1rTa3kuYu3rwuSVUTgZme8eKpGCAAaKjJrI74gdCo5yHapyc4a
LLyrNlu5yKSq6MG4nAXkIQMzOD8RvRc5dxqN0+4+6uPlvtsjuVJnxwwUVyvCUD54
619RpjFDQfo9rX0+AMkgR6M=
-----END PRIVATE KEY-----
</key>
EOF

uci -q commit openvpn
