#!/bin/sh

[ -f /etc/.config.lock ] && exit 0

uci batch << EOF
add_list firewall.@zone[1].network='azp'
del_list firewall.@zone[1].network='wan6'
commit firewall
EOF

[ -x /usr/bin/youtubeUnblock ] && {

cat << 'EOF' >> /etc/firewall.user
# Youtube Unblock
ytub(){
for ipt in iptables ip6tables; do
        $ipt -t mangle -N YT_UNBLOCK
        $ipt -t mangle -A YT_UNBLOCK -p tcp --dport 443 \
                -m connbytes --connbytes-dir original --connbytes-mode packets \
                --connbytes 0:19 -j NFQUEUE --queue-num 537 --queue-bypass
        $ipt -t mangle -A YT_UNBLOCK -p udp \
                -m connbytes --connbytes-dir original --connbytes-mode packets \
                --connbytes 0:8 -j NFQUEUE --queue-num 537 --queue-bypass
        $ipt -t mangle -A POSTROUTING -j YT_UNBLOCK
        $ipt -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT
done
}
ytub
EOF
}
