#!/bin/sh

cat << 'EOF' >> /etc/firewall.user
# Youtube Unblock
for ipt in iptables ip6tables; do
	$ipt -t mangle -I FORWARD \
		-p tcp --dport 443 -m connbytes \
		--connbytes-dir original \
		--connbytes-mode packets \
		--connbytes 0:19 -j NFQUEUE \
		--queue-num 537 --queue-bypass
	$ipt -I OUTPUT -m mark --mark 32768/32768 -j ACCEPT
done
EOF

uci batch << EOF
set firewall.@zone[1].network='wan wwan azp'
commit firewall
EOF
