#!/bin/sh

if ! [ -x /usr/sbin/wpad -o -x /usr/sbin/hostapd ]; then
	exit 0
fi

board="$(cat /tmp/sysinfo/board_name)"

case $board in
        zbtlink,zbt-we2802d-8m|\
        zbtlink,zbt-we2802d-16m|\
        zbtlink,zbt-we2806-a-8m|\
        zbtlink,zbt-we2806-a-16m)
                MACHINE=$(awk '{print $1}' /sys/firmware/devicetree/base/model)
        ;;
        *)
                MACHINE=$(awk '{print $2}' /sys/firmware/devicetree/base/model)
        ;;
esac

SUFFIX=$(awk -F [:] '{print toupper($4$5$6)}' /sys/class/net/eth0/address)

# 5 radios enough devices :)
enable_wifi(){
	for r in $(seq 0 5); do
		case $(uci -q get wireless.radio${r}.band) in
			2g)
				uci -q set wireless.radio${r}.country='RU'
				uci -q set wireless.radio${r}.noscan='1'
				uci -q set wireless.default_radio${r}.ssid=${MACHINE}_2G_${SUFFIX}
				uci -q delete wireless.radio${r}.disabled='1'
			;;
			5g)
				uci -q set wireless.radio${r}.country='RU'
				uci -q set wireless.default_radio${r}.ssid=${MACHINE}_5G_${SUFFIX}
				uci -q delete wireless.radio${r}.disabled='1'
			;;
		esac
	done

	uci -q commit wireless
	wifi
}

# More chips slowly start radio
sleep 30 && enable_wifi &
